### ISSUE TITLE
Add "delete" icon to delete single message

### ISSUE THREAD

**Issue by ThiloteE** [InAnYan/jabref#136]
![image](https://github.com/user-attachments/assets/359089ac-83fe-439d-8611-3ec6ac81519e)

**Comment by ThiloteE** [comment]
See also discussion at https://github.com/InAnYan/jabref/issues/118#issuecomment-2274062239

**Comment by InAnYan** [comment]
I like this UI feature **as a user**, but as a programmer I need to think how this system should be implemented.

You see, chat history is not a set, because ordering is important. Moreover it's not just a list:
1) Every message is dependent on previous messages. And this affects how AI will respond.
2) In ideal situatuation (and actually it's not that ideal, it's the common case), the chat history looks like this: "User message", "AI message", "User message", "AI message".

Considering all of those points, we need to semantically define what "deleting" is, what is their restrictions.

Currently, I see these options:
1. A delete button that can delete whatever message: 
    1. This will violate 1) and 2) points. Messages can be either "AI"; "AI; "AI" or "User"; "User"; "User".
    2. May affect AI output. What if some message contains some information referenced later, 
and then user decides to delete the source, then what's next?
    3. This option is easy to implement
2. A delete button that deletes only **one** last messages.
    1. This won't severely violate 1) and 2) points. But it may leave unanswered user question. 
    2. Should be easy to implement, but the first way is easier
3. A delete button that deletes only **two** last messages.
    1. This fully preserves 1) and 2) points
    2. But it may confuse user, that two messages were deleted

Maybe, it's not that important or severe, as I think

**Comment by InAnYan** [comment]
I think in this situation we can analyze, what other programs, companies did.

OpenAI ChatGPT (https://chatgpt.com), doesn't allow you to delete messages

**Comment by InAnYan** [comment]
Ah, you know, let's implement the first approach (delete button to everything, because it's easy)

**Comment by ThiloteE** [comment]
Try LMStudio, which implemented "1." and allows you to delete any message, regardless if from user or from model. It works fine. The quality of responses in this case depend on the language model, if it is trained on conversations like "user -> user -> model". The application should not be the limiting factor here, but the model. Even with mistral 7b, which is a lot worse than gpt4, the degradation in responses is not severe enough to be felt easily by users.

**Comment by InAnYan** [comment]
Closing, as implemented
