### ISSUE TITLE
Saving and loading of chat history should be a `logic` action

### ISSUE THREAD

**Issue by InAnYan** [InAnYan/jabref#15]
**Is your suggestion for improvement related to a problem? Please describe.**

Saving and loading of chat history is a `logic` action.

But the `logic` layer doesn't have the facilities to integrate new loading and storing actions (or, maybe, I haven't found it).

In the `GUI` layer there are `GUIPostOpenAction` and `SaveDatabaseAction`. These classes where a convenient place to implement the chat history saving and loading. 

**Describe the solution you'd like**
As the title says, saving and loading of chat history should be a `logic` action.

@koppor said, that the Carl is working on moving saving/loading code from `GUI` to `logic`. Guess, we have to wait.

What we have know is a workaround that works correctly.

**Comment by koppor** [comment]
> But the logic layer doesn't have the facilities to integrate new loading and storing actions (or, maybe, I haven't found it).

Just create the methods there and call them at `SaveDatabaseAction`. The GUI layer is the place to call logic actions.

The reason why `org.jabref.gui.exporter.SaveDatabaseAction#saveDatabase` is still in the UI is the undo manager (see line 276). 

As a coding excercise one could move the methods `saveDatabase` to somewhere in  `logic`. But it is a rabbit hole, because `org.jabref.logic.autosaveandbackup.BackupManager.performBackup` also needs to be adapted then.

**Comment by InAnYan** [comment]
Closed because of using MVStore #48.
